name: Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}
    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "jruby-9.4.8.0"
        gemfile:
          - gemfiles/ar72.gemfile
          - gemfiles/ar71.gemfile
          - gemfiles/ar70.gemfile
        channel: ['stable']
        include:
          - ruby: head
            gemfile: gemfiles/ar71.gemfile
            channel: 'experimental'
          - ruby: head
            gemfile: gemfiles/ar72.gemfile
            channel: 'experimental'
          - ruby: jruby-head
            gemfile: gemfiles/ar71.gemfile
            channel: 'experimental'
          - ruby: jruby-head
            gemfile: gemfiles/ar72.gemfile
            channel: 'experimental'
    continue-on-error: ${{ matrix.channel != 'stable' }}
    steps:
      - name: Set Up Gems
        uses: actions/checkout@v4
      - name: Set Up Deps
        run: sudo apt-get install libgeos-dev
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake
